DROP TABLE IF EXISTS room_301;
DROP TABLE IF EXISTS room_302;
DROP TABLE IF EXISTS room_303;
DROP TABLE IF EXISTS room_401;
DROP TABLE IF EXISTS room_402;
DROP TABLE IF EXISTS room_404;
DROP TABLE IF EXISTS room_405;
DROP TABLE IF EXISTS room_406;
DROP TABLE IF EXISTS room_407;
DROP TABLE IF EXISTS room_408;
DROP TABLE IF EXISTS room_409;
DROP TABLE IF EXISTS room_411;
DROP TABLE IF EXISTS room_412;

CREATE TABLE room_301 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_302 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_303 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_401 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_402 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_404 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_405 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_406 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_407 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_408 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_409 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_411 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);

CREATE TABLE room_412 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	last_alteration DATE DEFAULT (datetime('now','localtime')),
	name TEXT NOT NULL,
	general_status INTEGER NOT NULL DEFAULT 0, /* OK, MONITOR, COMPUTADOR, REDE, REDE + POWER, POWER */
	monitor_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	monitor_status TEXT NOT NULL DEFAULT 'EMPTY',
	case_config TEXT NOT NULL DEFAULT 'EMPTY', /* SE REMOVIDO, REMOVE TAMBÉM > OS, MOTHERBOARD, CPU, MEMORY, STORAGE */
	case_status TEXT NOT NULL DEFAULT 'EMPTY',
	keyboard_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	keyboard_status TEXT NOT NULL DEFAULT 'EMPTY', 
	mouse_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	mouse_status TEXT NOT NULL DEFAULT 'EMPTY',
	os_config TEXT NOT NULL DEFAULT 'EMPTY', /* SÓ TROCAR */
	os_status TEXT NOT NULL DEFAULT 'EMPTY',
	network_config TEXT NOT NULL DEFAULT 'EMPTY', /* POSSO REMOVER */
	network_status TEXT NOT NULL DEFAULT 'EMPTY'
);